# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# RasterMosaicClip.py
# Created on: 2016-05-19 09:55:18.00000
# Generated by ArcGIS/ModelBuilder and edited for ArcPy
# Usage: RasterMosaicClip <Save_File_Geodatabase> <Output_File_Geodatabase> <Coordinate_System> <Output_Mosaic_Shell_Dataset> <Mosaic_Dataset_Output> <Clipping_Feature__Watershed_Boundary_> <Clipped_DEM_Output> <Hillshade_Output>
# Resources: <Raster Iteration> http://stackoverflow.com/questions/30043403/create-for-loop-to-process-multiple-rasters-in-a-file-using-arcpy-clip-managemen /// http://gis.stackexchange.com/questions/100184/batch-raster-conversion
# /// https://geonet.esri.com/thread/101390 /// https://pubs.usgs.gov/of/2013/1015/downloads/3_MosaicRasters.py
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy.sa import *
arcpy.CheckOutExtension("Spatial")

arcpy.env.overwriteOutput = True

#sa = arcpy.SpatialReference(102003)

# Local Variables
gdb_path = arcpy.GetParameterAsText(0) # path: "D:/PYDEM/GDB"
gdb_name = arcpy.GetParameterAsText(1) # name: "River_Mosaic.gdb"
mosaic_dataset = arcpy.GetParameterAsText(2) # name: "River_Mosaic"
mosaic_cs = arcpy.GetParameterAsText(3) # projection: North_America_Albers_Equal_Area_Conic.prj
clip_shp = arcpy.GetParameterAsText(4) # clipping feature: "D:/LittleMissouri_River_Typing/01_Boundaries/01_Watershed/LittleMissouri_Watershed.shp"
dem_in = arcpy.GetParameterAsText(5) # projected DEMs folder: "D:/PYDEM/Proj_DEM2/"
dem_out = arcpy.GetParameterAsText(6) # Clipped DEM:"D:/PYDEM/GDB/DEM_Test.tif"
hill_out = arcpy.GetParameterAsText(7) # Hillshade: "D:/PYDEM/GDB/Hill_Test.tif"

# Process: Create File GDB
arcpy.CreateFileGDB_management(gdb_path, gdb_name)

arcpy.AddMessage("File geodatabase created!")

# Process: Create Mosaic Dataset
arcpy.CreateMosaicDataset_management(gdb_path + "\\" + gdb_name, mosaic_dataset, mosaic_cs, "1", "32_BIT_FLOAT", "NONE", "")

arcpy.AddMessage("Mosaic dataset created!")
arcpy.AddMessage("Adding rasters to mosaic dataset")

# Process: Add Rasters To Mosaic Dataset
arcpy.env.workspace = dem_in
dem_list = arcpy.ListRasters()
for raster in dem_list:
    arcpy.AddMessage("Adding " + raster + " to mosaic dataset")
    arcpy.AddRastersToMosaicDataset_management(gdb_path + "\\" + gdb_name + "\\" + mosaic_dataset, "Raster Dataset", raster)

# Process: Clip DEM
arcpy.AddMessage("Clipping DEM...")
arcpy.Clip_management(gdb_path + "\\" + gdb_name + "\\" + mosaic_dataset, "#", dem_out, clip_shp, "#", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Hillshade
arcpy.AddMessage("Creating hillshade and clipping to extent...")
arcpy.gp.HillShade_sa(dem_out, hill_out, "315", "45", "NO_SHADOWS", "1")

arcpy.AddMessage("Processing complete!")